apiVersion: v1 
kind: Pod 
metadata: 
    name: mydev
    labels:
      app: devshell
spec:
    initContainers:
      - name: set-home-dir-perms
        image: alpine:3.6
        command: [ 'chmod', '755', '/home']
        volumeMounts:
          - name: docker-home-storage
            mountPath: /home
    containers:
      - name: mydev 
        image: timrodocker/devshell:v0.7
        env: 
          - name: DOCKER_HOST 
            value: tcp://localhost:2375
          - name: DEVUSER
            valueFrom:
              secretKeyRef:
                name: dev-creds
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-creds
                key: password
        volumeMounts: 
          - name: docker-home-storage 
            mountPath: /home
      - name: dind-daemon 
        image: docker:dind 
        resources: 
            requests: 
                cpu: 50m 
                memory: 512Mi 
        securityContext: 
            privileged: true 
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker
          - name: docker-home-storage 
            mountPath: /home 
    volumes: 
      - name: docker-graph-storage 
        persistentVolumeClaim:
          claimName: "dockervol"
      - name: docker-home-storage 
        persistentVolumeClaim:
          claimName: "dockerhome"