apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "dockervol"
  labels: 
    app: devshell
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "dockerhome"
  labels: 
    app: devshell
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "20Gi"